language: rust
rust:
- stable
- beta
- nightly
os:
  - linux
  - osx
  - windows
cache: cargo
matrix:
  fast_finish: true
script:
  # VERSION variable is accessed as CARGO_PKG_VERSION
  - export HASH=$(git rev-parse --short HEAD)
  - export BUILD_AT="$(date date --iso-8601=seconds)"

  - cargo test --bin ff -- --test-threads=1
  - cargo build --verbose --all-features
  - cargo build --verbose --release
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        cp target/release/ff.exe "./ff_${TRAVIS_OS_NAME}.exe" ;
        ;;
      linux|osx)
        cp target/release/ff "./ff_${TRAVIS_OS_NAME}" ;
        ;;
    esac

deploy:
  provider: releases
  api_key:
    secure: fEOkvPUHoEtA4RJWkfNDfzU+NiXZKqor6doiAs/58CKFVeEv2iaCJtlv/1nbaBvzj/uXMJ6PPajKzPegG4nLVo+BRJ/Pzj7UuvGCUhKc4zBhhh4kSk/hGkXSjxpyJ/WvzgO2M/4PyLeXzw4DevBZ1cfAn/g+dkExWezahz3n+ICMd93hJIIX+jcELCnFzsJFm2qDxYfanoYiDPSSwujdOrEiIkhjx4+WjRwWGeaAisB4Dr0JnT6w4IHQ2GYoZvi6XOJcADHhz1cH3EEWdp4qPubha7kYmfb7246Ud8MoTUIk1FXcN0fD9N3dzbKs3PRT5gY/A1h9cGBwD4RUnAAIhCr2b1AVNHQAkY+05AMHJuqHHq1n+5SvSkiQz3VhZqC76bxmniqhiPhqcu/QRBfohNqqc8DIdDiJcalvw+xflNcEZIi7rKowF/DQmD/wGox4wYRnRbFVokI0lgnwQVN1GOS0EApfk+Q+XoxJxMfx+P7e2EEZ5RC4FL+TSiUfDPKGJHymOAc1tue0x44FJteWpyHT4Ybv5IpS4jvKXEfzeKzBfY8fIZZYtbrIEcHxv9NeOb0IhZMMpGUtCiJyl8an3d8HrLw429eeB1E+F7ebe/P9Sulwf3P6JXbbqj1tx1tYbaZnF2lys98ejVtl67Vl9PZ1smu1ofqe4BBg+iorZfU=
  file:
    - "ff_linux"
    - "ff_osx"
    - "ff_windows.exe"
  draft: true
  on:
    tags: true
