language: rust
rust:
- stable
- beta
- nightly
os:
  - linux
  - osx
  - windows
cache: cargo
matrix:
  fast_finish: true
script:
  - export VERSION="$TRAVIS_TAG"
  - export HASH=$(git rev-parse --short HEAD)
  - export BUILD_AT="$(date --iso-8601=seconds)"

  - |-
    case $TRAVIS_OS_NAME in
      windows)
        curl -L https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msys2-2.7.0-x64.tar.gz > winpty-0.4.3-msys2-2.7.0-x64.tar.gz ;
        7z e winpty-0.4.3-msys2-2.7.0-x64.tar.gz && 7z x winpty-0.4.3-msys2-2.7.0-x64.tar ;
        export PATH="$PATH:$(pwd)/winpty-0.4.3-msys2-2.7.0-x64/bin" ;
        uname -a ;
        which bash ;
        which cmd ;
        which powershell ;
        which winpty.exe ;
        winpty.exe -Xallow-non-tty -Xplain cargo test --bin ff -- --test-threads=1 ;
        ;;
      linux|osx)
        cargo test --bin ff -- --test-threads=1 ;
        ;;
    esac

  - cargo build --verbose --all-features
  - cargo build --verbose --release
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        cp target/release/ff.exe "./ff_${TRAVIS_OS_NAME}.exe" ;
        ;;
      linux|osx)
        cp target/release/ff "./ff_${TRAVIS_OS_NAME}" ;
        ;;
    esac

deploy:
  provider: releases
  api_key:
    secure: sGusYxVipqKw3nEzWeLs3lrRSflwF6GYry+3rS/OfkJrhDZnHUveOshbPDIFlMbquGS8EPBxZqgMXiINtUKaHQ5LW+ZkpBY4B1/MxpZpAg1gpNbX/EguddwUDk/RncE25At2dzOVrylpDq98UMYUNSY3H+WXp3RvVlH6m3r/pzOlu360Ew0xBsCn/041MAXhOza9gP9qJtdXa+UFB7ejCRVm0X+8u0n7H7ZP3CfGUtcOOUOn675s3a1gNGKkFl/F8RHu7X4bV2pa+kjNyahdLScaVaZE6+wGroJNKrJzdXmMq098NXKnXE7Sr+f2RD8K4kFTuhJzqkkfC2M6/s7JVwBetOSSS1WzPiy+dBzGHC/kPjvjCLu6uhhXHNXbyKFu6gQtVxDNzx7tqQjGA/TUlvv+FxuufYJkcuQrFv1cqjBfvB4+ibdZ+sctAa54YQ8EJ0sCg+7WH7DXz1OlpRQ6AL0mZA8+GBf3fC7mX7tEKlsjqLd7027xF4YK2314Fy9xcgEkjExUGpGl5RbKYRDMqTrIwQnW71VK0ZqrugkbJq+tSnL3uHzqqPgcyXiGw8pnMvRvZ4ay3hXXDXWDzhPNoKCKoO5GXQ0DyF75Jq7amxn9uH8s5K30nG0ydSjDlVC03jdNvU2tTFemS5cATJXRUsGFUzO9EQPAPg+XwybLjW8=
  file:
    - "ff_linux"
    - "ff_osx"
    - "ff_windows.exe"
  skip_cleanup: true
  draft: true
  on:
    tags: true
