language: rust
rust:
- stable
- beta
- nightly
os:
  - linux
  - osx
  - windows
cache: cargo
matrix:
  fast_finish: true
script:
  # VERSION variable is accessed as CARGO_PKG_VERSION
  - export HASH=$(git rev-parse --short HEAD)
  - export BUILD_AT="$(date date --iso-8601=seconds)"

  - cargo test --bin ff -- --test-threads=1
  - cargo build --verbose --all-features
  - cargo build --verbose --release
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        cp target/release/ff.exe "./ff_${TRAVIS_OS_NAME}.exe" ;
        ;;
      linux|osx)
        cp target/release/ff "./ff_${TRAVIS_OS_NAME}" ;
        ;;
    esac

deploy:
  provider: releases
  api_key:
    secure: "vHSobZwxHGTy8+nmvC6xCrjcEQw0WoV6GeCCYcohUHrWeSK/gPMT9NK9zo/MHyO5y2xfqksDHVCBBw/x0i5OjUDWN+pLt4csvVDC5/tM9pkWXaMKcfdzENoVeCcYdO9aZmvAhmJqh1tqKuwK746jzeO3skJAI+85cR7UvSOcwCGcY9SWCd0WUSRyucvMBXlmlnfHoI67EH+mygaRqJ3DUaUAhduRuYR73OVpGdaGwWFl/vrZ8sKz8ptUm+zkd/LwCn7Wzqk7aobnS8oF739asZyC+xKKXhoxGMUF8wy9h4ZRPpUIHO3xFzmmMQFNYQsO9UO5wv1lPDjM6eUgALSDgBTnvBHnXp07TMAzYqVdIgDJFeo7LNY+XRbG4hLWHVvgWXizSlDzilayUQ/ojRhv3nrNFT/ia6NDeQOGAMsf0snxn1Da7K9jyw/WdA+XBNnSKRHdC4qIfgp2I3GB/pMR05qvro5O3MxP0ktpc4Hz0wN4iN2tMo/zTp2xDzsD1i85OAjexPXXgZAkvYOspzb3MJGIx6prmL+w+07ayLcXYlsQ+EQBx2BB5K5F6AMe4khRpOklrFMFYkmoN1PKT1Qpy5ZPVB+RL8xJoJHU/45Cn19KyzkO99ODy1hvnX3fGFoAoHZE28X/KcfCp/d+dKeUys8QAfWrSIaz5o70/6LH484="
  file:
    - "ff_linux"
    - "ff_osx"
    - "ff_windows.exe"
  skip_cleanup: true
  draft: true
  on:
    tags: true
