language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
cache: cargo
matrix:
  fast_finish: true
script:
  - export VERSION="$TRAVIS_TAG"
  - export HASH=$(git rev-parse --short HEAD)
  - export BUILD_AT="$(date --iso-8601=seconds)"

  - cargo test --bin ff -- --test-threads=1 ;
  - cargo build --verbose --release

  - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then export EXTENSION=.exe ; fi
  - cp "target/release/ff${EXTENSION}" "./ff_${TRAVIS_OS_NAME}_${VERSION}${EXTENSION}"

deploy:
  provider: releases
  api_key:
    secure: gKGL8hPPqYlsqmPXVchxJVxVYzQVHPqELEb74D09ELUFjEX7wXAVGj9R8eptis14BiCMwairegMp417YsfT8qTZHI+cYcoVqyKsuvFo6E+pjNxJW9YMNVPZy2SA2B/tvrnNlNEkNpz5bPjJZwSBchRvja61miSsIL4slL83X3Sah9OhxDBJ0enYPxlBbF76w/ykUm2R0SeOM7LNAUlAApUJOdaSD4SJC/Sie45bCedd6eWlPbjy/FRq/2rO3fsnboWp8MbQogNXLCrfzLOyzsRhcI9IxB5SiaM/jq0o7M7w0eMnd35JroNGpUx+AB6/ZdottGgbxa/mUqUULH9Xy4G1UeQBBNRM7doUOhdt0lE0qaJMhz0WHbFFV6Q2ZtxjSQy66oHeUKzN8a3X8ECN/A9F8VEH7r2YhsagDsCmF3kEbxSF6EkVClkrErqUVHIG+JJhNbYkxfAz4ClCL111rvunsVhfiQAEOU8WaSD+tUp0iIDxK6ttxStZYEZvhwd6UTDrRicIW0RYse6FF5svV7wn6V6Gq4QKLnGplCvWMSwNcE47Vm5hoj1Z03piOUlquOfBffmAhUMOOBwH5P9CPdfKXK7iGZru+a7LOx61UN2KLpsBTdjb1uKCB+A2mz3vjPuMqPSwyr0rmDiyvhOgMsn4mk7zjeYMWfspaqyik2vk=
  file_glob: true
  file: ff_*
  skip_cleanup: true
  draft: true
  on:
    tags: true

