language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
cache: cargo
matrix:
  fast_finish: true
script:
  - export VERSION="$TRAVIS_TAG"
  - export HASH=$(git rev-parse --short HEAD)
  - export BUILD_AT="$(date --iso-8601=seconds)"

  - cargo test --bin ff -- --test-threads=1 ;
  - cargo build --verbose --release

  - if [ "$TRAVIS_OS_NAME" = "windows" ] ; then export EXTENSION=.exe ; fi
  - cp "target/release/ff${EXTENSION}" "./ff_${TRAVIS_OS_NAME}_${VERSION}${EXTENSION}"

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: ff_*
  skip_cleanup: true
  draft: true
  on:
    tags: true

