[package]
name = "ff"
version = "1.1.0"
authors = ["Ivan Latunov <xswordsx@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
atty = "0.2"
chrono = "0.4"
getopts = "0.2"
json = "0.11"
yaml-rust = "0.4"
assert_cmd = "1.0"
paste = "0.1.18"